### ISSUE TITLE
`./deps/` folder is archaic

### ISSUE THREAD

**Issue by shiney-wh** [nil0x42/phpsploit#41]
I wonder why this directory exist.

For example, i need to use yaml format and i can't find an easy way.
Indeed, PyYaml need multiple dependencies and it's annoying to download and include each of them.
Why don't use requirement.txt ?
Or virtualenv ?

**Comment by nil0x42** [comment]
i agree with you, the deps/ folder made things easier in the past, but is no longer a good practice.
i ll consider removing it next month.

therefore, i am curious about your needs on Yaml, because i d like to limit dependencies as much as possible

**Comment by shiney-wh** [comment]
I am working on new plugin called "sensitive".

It aim to find sensitive file or folder in the remote server. (ssh keys, backup files, ftp password ...)
Rules are written as yaml:
```yaml
#
#  *       : any directory
#  *!(a|b) : any path except a and b
rules:
  match_path:
    - "/root/*/.ssh"
    - "/home/*/.ssh"
    - "/var/www/.ssh"
    - "/*!bin|boot|build|cdrom|dev|etc|home|lib|lib32|lib64|lost+found|media|mnt|opt|proc|root|run|sbin|srv|sys|tmp|usr|var"
  vcs:
    - "/var/www/*/*/.git"
    - "/var/www/*/.git"
    - "/home/*/*/*/*/.git"
    - "/home/*/*/*/.git"
    - "/home/*/*/.git"
```
